### ISSUE TITLE
[Enhancement] Only clone the requested tag/commit

### ISSUE THREAD

**Issue by ReimuNotMoe** [cpm-cmake/CPM.cmake#200]
Currently CPM clones the entire git repo on `CPMAddPackage`. This is slow for a large repo.

It would be better if CPM can clone only the requested tag/commit. e.g. `git clone <remote> -b <rev> --depth=1 --single-branch`.

**Comment by TheLartians** [comment]
Hey thanks for the issue! Shallow cloning is already enabled by default, but only with [`CPM_SOURCE_CACHE`](https://github.com/cpm-cmake/CPM.cmake#CPM_SOURCE_CACHE) enabled (recommended). The reason is that otherwise git will error if a tag changed after configuration. See #129 for the full discussion.
