### ISSUE TITLE
Infer package name from URL

### ISSUE THREAD

**Issue by iboB** [cpm-cmake/CPM.cmake#208]
#181 is about inferring the version from a URL. It should be extended to also infer the name if not provided (much like #202 introduced inferring a name from a git repository).

If we can infer the name from a URL, fixing several lines in #207 (as indicated in the code), will allow URL-based packages to be added by the shorthand syntax .

@jhasse doesn't seem to be responding, so I volunteer to be assigned to this and move forward both version and name inference from URLs.

**Comment by jhasse** [comment]
hi, sorry for my silence. I currently don't have time to work on this so feel free to take over my PR.

**Comment by iboB** [comment]
I started working on this in [name-and-ver-from-url](https://github.com/cpm-cmake/CPM.cmake/tree/name-and-ver-from-url)

Should I preserver the logic to infer version in `CPMFindPackage`?

In fact, should we try to have a shorthand syntax for `CPMFindPackage` as well? If not, then should we at least try to infer the package name if not provided?

**Comment by iboB** [comment]
@TheLartians what do you think about the `CPMFindPackage` question?

If we decide the to support it too, I think the best way to go is to create a macro (not a function) to parse and check the common arguments.

**Comment by TheLartians** [comment]
While I'm personally not a big fan of `CPMFindPackage` (you would need to support all dependency versions that could potentially be found on a user's system), I do see that some prefer it, e.g. to save some build time. I think having a unified syntax for both does make sense, as it does appear counter-intuitive otherwise.

Probably using a common macro to handle arguments in both functions is a good idea to avoid unnecessary code or code duplication. As usual with macros, we should take care not to export any unexpected variables into the scope.

**Comment by iboB** [comment]
Check... well in this case, I intend to open the PR for single-arg-URLs as it is (with no changes to `CPMFindPackage`) and then work on #219 to add the shorthand support to  `CPMFindPackage`
