### ISSUE TITLE
Shouldn't OPTIONS be stored in CACHE?

### ISSUE THREAD

**Issue by OlivierLDff** [cpm-cmake/CPM.cmake#290]
Hi, maybe I'm not using CMake as expected, but I'm never using `option` function.
Instead I define my option like that:

```cmake
set(MYLIB_ENABLE_TESTS OFF CACHE BOOL "Create Unit Tests")
set(MYLIB_FOLDER_PREFIX "Prefix" CACHE STRING "PROPERTIES FOLDER for all MyLib target")
```

So I have consistent option declaration no matter the option type. And it seems I'm not [alone](https://stackoverflow.com/questions/8709877/cmake-string-options).

When I was using `FetchContent`, I was simply copying and pasting the `set(...)` function call to customize the value. I wanted to give a shot at `OPTIONS` from CPM but the script doesn't write variable in CACHE.

https://github.com/cpm-cmake/CPM.cmake/blob/ea6a8eb8959e06a576c1843750f03ce28c0b0121/cmake/CPM.cmake#L743

I guess major drawback of writing the cache is destroying some variable of upper project when variable are not namespaced?
This example wouldn't work with my CACHE approach:

```cmake
cmake_minimum_required(VERSION 3.14.0 FATAL_ERROR)
project(MyProject)

option(BUILD_TESTING "Build my cool unit test" ON)

CPMAddPackage(
  NAME SomeLibrary
  OPTION "BUILD_TESTING OFF"
)

if(BUILD_TESTING)
  add_subdirectory(mytest)
endif()
```

My question are:
* Am I doing something wrong by not using `option`?
* Do I have some alternate choice of what I'm already doing, ie `set(MYLIB_ENABLE_TESTS OFF CACHE BOOL "Create Unit Tests")` then `CPMAddPackage`
* I answered myself by giving the example, that it is not a good idea for CPM to write OPTIONS variable in CACHE

**Comment by TheLartians** [comment]
We did initially set the passed options in the cache (and even had some consistency checking code), but decided to switch to scoped options after former turned out to be confusing and error-prone for end users (often due to library authors not namespacing options see e.g. #222).

> Am I doing something wrong by not using `option`?

Really depends on what you want to achieve, imho `option` is the best choice for boolean parameters.

> Do I have some alternate choice of what I'm already doing, ie `set(MYLIB_ENABLE_TESTS OFF CACHE BOOL "Create Unit Tests")` then `CPMAddPackage`

If you really need non-boolean options for your project you could consider to add a guards around them. This should allow CPM.cmake to override the values through scoped variables.

```cmake
# allow scoped overriding by parent packages
if (NOT DEFINED MYLIB_ENABLE_TESTS)
   set(MYLIB_ENABLE_TESTS OFF CACHE BOOL "Create Unit Tests")
endif()
```

On the other hand, I also don't see anything wrong with being explicit and setting a cache option before the `CPMAddPackage` call as you're currently doing.

> I answered myself by giving the example, that it is not a good idea for CPM to write OPTIONS variable in CACHE

Precisely

**Comment by OlivierLDff** [comment]
Ok thanks for the precision.
From what I understand:
* I should use `option` for boolean as this is the de facto cmake way of creating boolean options
* STRING option are more rare, so it is ok to write explicitely in CACHE before `CPMAddPackage`

Thanks for the quick feedback, have a nice evening!
