### ISSUE TITLE
Editable packages

### ISSUE THREAD

**Issue by izzyreal** [cpm-cmake/CPM.cmake#395]
Is there a flow where things included with CPM are editable?

I have 2 projects that I maintain: `ctoot` and `moduru`. `ctoot` depends on `moduru`. `moduru`'s `CMakeLists.txt` has a static lib target that `ctoot` consumes, as well as a `moduru-tests` executable target. When I create a Visual Studio solution for `ctoot`, that solution should include all the targets from `moduru`, so I can work on the `moduru` library itself and run `moduru`'s unit tests while doing so.

When I link `moduru` to `ctoot` via `target_link_libraries`, the `moduru` target appears in my Visual Studio solution's project explorer. So far so good.

However, `moduru-tests` does not appear, which I suppose makes sense, considering a CMake dependency graph can easily contain many transient executable targets for unit tests, examples, etc. Is there a way to expose all or user-selected targets of a package that is included via CPM?

See https://github.com/izzyreal/ctoot/blob/no-conan/CMakeLists.txt and https://github.com/izzyreal/moduru/blob/no-conan/CMakeLists.txt

**Comment by TheLartians** [comment]
I don't use Visual Studio, but I think the issue is that the target is not added to the default CMake build target `all`. This can be resolved by explicitly setting the `EXCLUDE_FROM_ALL` flag to `NO` in the explicit API. In the single-argument API, the argument defaults to `YES`. 

You can try changing `CPMAddPackage("gh:izzyreal/moduru#no-conan")` to the following to have all targets added to the `all` target:

```cmake
CPMAddPackage(
  NAME moduru
  GITHUB_REPOSITORY izzyreal/moduru
  GIT_TAG no-conan
  EXCLUDE_FROM_ALL NO # actually optional here, as it defaults to false on the explicit syntax
)
```

**Comment by izzyreal** [comment]
Thanks, I may try that, though currently I'm experimenting with `FetchContent`.
